// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljqqcgnibdbjxptvsqgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqcXFjZ25pYmRianhwdHZzcWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDQyNTMsImV4cCI6MjA1NTk4MDI1M30.dCItjyzh1-SukNrH2kryyv_aaz-WuUVNZxY4vwfVxpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);